from __future__ import annotations

import json
import re
from pathlib import Path
from typing import Any

import pandas as pd

from .config import RSAConfig


PIPELINE_NAME = "rsa-toolbox"
BIDS_VERSION = "1.11.1"


def write_bids_dataset_description(
    bids_root: str | Path,
    source_root: str | Path | None = None,
) -> Path:
    """Write dataset-level metadata for the BIDS derivatives export."""

    bids_root = Path(bids_root)
    bids_root.mkdir(parents=True, exist_ok=True)
    description = {
        "Name": "TAY-RSA physiology derivatives",
        "BIDSVersion": BIDS_VERSION,
        "DatasetType": "derivative",
        "GeneratedBy": [
            {
                "Name": PIPELINE_NAME,
                "Description": "Python toolbox for raw MindWare ECG decoding, R-peak detection, IBI artifact correction, RSA/HRV metrics, QC, and nonlinear feature extraction.",
            }
        ],
        "ReferencesAndLinks": [
            "https://bids-specification.readthedocs.io/",
            "https://github.com/Cognemo-lab/TAY-RSA",
        ],
    }
    if source_root is not None:
        description["SourceDatasets"] = [{"URL": str(Path(source_root).expanduser())}]
    path = bids_root / "dataset_description.json"
    path.write_text(json.dumps(description, indent=2) + "\n", encoding="utf-8")

    readme = bids_root / "README"
    if not readme.exists():
        readme.write_text(
            "\n".join(
                [
                    "TAY-RSA BIDS derivatives",
                    "",
                    "This derivative dataset was generated by rsa-toolbox.",
                    "It contains preprocessed RSA/HRV physiology outputs organized by BIDS subject/session labels.",
                    "",
                    "Tables with the suffix _timeseries.tsv contain derivative tabular outputs with headers.",
                    "R-peak detections are written as _events.tsv files with onset and duration columns.",
                    "Column definitions and processing provenance are stored in JSON sidecars.",
                    "",
                ]
            ),
            encoding="utf-8",
        )
    return path


def write_bids_participants(bids_root: str | Path, subject_rows: list[pd.DataFrame]) -> Path | None:
    """Write a minimal participants table from processed subject/session rows."""

    if not subject_rows:
        return None
    bids_root = Path(bids_root)
    combined = pd.concat(subject_rows, ignore_index=True, sort=False)
    participants = (
        combined[["subject_id"]]
        .drop_duplicates()
        .assign(participant_id=lambda df: df["subject_id"].map(lambda x: f"sub-{_bids_label(x)}"))
        [["participant_id"]]
        .sort_values("participant_id")
    )
    path = bids_root / "participants.tsv"
    participants.to_csv(path, sep="\t", index=False)
    _write_json(
        path.with_suffix(".json"),
        {
            "participant_id": {
                "Description": "BIDS participant identifier derived from the recording subject identifier.",
            }
        },
    )
    return path


def write_bids_derivatives(
    bids_root: str | Path,
    recording_id: str,
    source: str,
    metrics: pd.DataFrame,
    qc: pd.DataFrame,
    nonlinear_features: pd.DataFrame | None,
    mse_curve: pd.DataFrame | None,
    subject_features: pd.DataFrame,
    config: RSAConfig,
    metadata: dict[str, Any] | None = None,
    raw_peaks: pd.DataFrame | None = None,
    raw_ibi: pd.DataFrame | None = None,
    task_label: str = "rest",
) -> dict[str, Path]:
    """Write BIDS-derivative style physiology outputs for one recording."""

    bids_root = Path(bids_root)
    entities = _entities_from_recording(recording_id, task_label)
    out_dir = bids_root / f"sub-{entities['sub']}" / f"ses-{entities['ses']}" / "physio"
    out_dir.mkdir(parents=True, exist_ok=True)
    stem = _entity_stem(entities)
    paths: dict[str, Path] = {}

    if raw_peaks is not None and not raw_peaks.empty:
        peaks = raw_peaks.copy()
        peaks.insert(0, "duration", 0.0)
        peaks.insert(0, "trial_type", "r_peak")
        peaks = peaks.rename(columns={"time_s": "onset"})
        cols = ["onset", "duration", "trial_type", "peak_index", "sample_index", "ecg_value", "detector_value"]
        if "qrs_energy" in peaks:
            cols.append("qrs_energy")
        path = out_dir / f"{stem}_recording-rsa_desc-rpeaks_events.tsv"
        _write_tsv(path, peaks[[c for c in cols if c in peaks]])
        _write_json(
            path.with_suffix(".json"),
            _sidecar(
                recording_id,
                source,
                "Detected R peaks from the raw ECG signal.",
                {
                    "onset": {"Description": "R-peak onset in seconds from recording start.", "Units": "s"},
                    "duration": {"Description": "Event duration. R peaks are modeled as impulses.", "Units": "s"},
                    "trial_type": {"Description": "Event type.", "Levels": {"r_peak": "Detected R peak"}},
                    "sample_index": {"Description": "Detected ECG sample index."},
                    "ecg_value": {"Description": "Calibrated ECG value at the detected peak."},
                    "detector_value": {"Description": "Filtered detector signal value at the detected peak."},
                    "qrs_energy": {"Description": "Derivative-squared QRS energy envelope at the detected peak."},
                },
                config,
                metadata,
            ),
        )
        paths["rpeaks_events"] = path

    if raw_ibi is not None and not raw_ibi.empty:
        ibi = raw_ibi.copy()
        ibi.insert(0, "onset", _ibi_onsets(ibi, config))
        path = out_dir / f"{stem}_recording-rsa_desc-preprocIbi_timeseries.tsv"
        _write_tsv(path, ibi)
        _write_json(
            path.with_suffix(".json"),
            _sidecar(
                recording_id,
                source,
                "Beat-level IBI derivative table. The corrected ibi_ms column is used by downstream HRV/RSA metrics.",
                {
                    "onset": {"Description": "Approximate beat onset in seconds from recording start.", "Units": "s"},
                    "segment": {"Description": "Thirty-second segment index."},
                    "beat_index": {"Description": "Beat interval index within segment."},
                    "raw_ibi_ms": {"Description": "Original IBI from detected R peaks.", "Units": "ms"},
                    "ibi_ms": {"Description": "Corrected IBI used for analysis.", "Units": "ms"},
                    "artifact_flag": {"Description": "Whether the raw IBI was flagged as an artifact."},
                    "artifact_reason": {"Description": "Reason for artifact flag."},
                    "corrected": {"Description": "Whether a corrected/interpolated IBI value was written."},
                },
                config,
                metadata,
            ),
        )
        paths["ibi_timeseries"] = path

    paths["segment_metrics"] = _write_table_with_sidecar(
        out_dir / f"{stem}_recording-rsa_desc-segmentMetrics_timeseries.tsv",
        _segment_onsets(metrics, config),
        recording_id,
        source,
        "Segment-level RSA/HRV metrics computed from the selected IBI series.",
        config,
        metadata,
    )
    paths["segment_qc"] = _write_table_with_sidecar(
        out_dir / f"{stem}_recording-rsa_desc-segmentQc_timeseries.tsv",
        _segment_onsets(qc, config),
        recording_id,
        source,
        "Segment-level QC table for the selected preprocessing pathway.",
        config,
        metadata,
    )

    if nonlinear_features is not None and not nonlinear_features.empty:
        paths["nonlinear"] = _write_table_with_sidecar(
            out_dir / f"{stem}_recording-rsa_desc-nonlinear_timeseries.tsv",
            _segment_onsets(nonlinear_features, config),
            recording_id,
            source,
            "Segment-level nonlinear IBI features.",
            config,
            metadata,
        )
    if mse_curve is not None and not mse_curve.empty:
        paths["mse"] = _write_table_with_sidecar(
            out_dir / f"{stem}_recording-rsa_desc-mse_timeseries.tsv",
            mse_curve,
            recording_id,
            source,
            "Full-recording multiscale entropy curve.",
            config,
            metadata,
        )

    feature_path = out_dir / f"{stem}_recording-rsa_desc-summary_features.tsv"
    _write_tsv(feature_path, subject_features)
    _write_json(
        feature_path.with_suffix(".json"),
        _sidecar(
            recording_id,
            source,
            "One-row subject/session RSA feature summary.",
            {"recording_id": {"Description": "Original recording identifier."}},
            config,
            metadata,
        ),
    )
    paths["summary_features"] = feature_path
    return paths


def _write_table_with_sidecar(
    path: Path,
    frame: pd.DataFrame,
    recording_id: str,
    source: str,
    description: str,
    config: RSAConfig,
    metadata: dict[str, Any] | None,
) -> Path:
    _write_tsv(path, frame)
    columns = {col: _column_description(col) for col in frame.columns}
    _write_json(path.with_suffix(".json"), _sidecar(recording_id, source, description, columns, config, metadata))
    return path


def _write_tsv(path: Path, frame: pd.DataFrame) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    frame.to_csv(path, sep="\t", index=False, na_rep="n/a")


def _write_json(path: Path, data: dict[str, Any]) -> None:
    path.write_text(json.dumps(data, indent=2) + "\n", encoding="utf-8")


def _sidecar(
    recording_id: str,
    source: str,
    description: str,
    columns: dict[str, Any],
    config: RSAConfig,
    metadata: dict[str, Any] | None,
) -> dict[str, Any]:
    sidecar: dict[str, Any] = {
        "Description": description,
        "Sources": [recording_id],
        "PipelineDescription": {
            "Name": PIPELINE_NAME,
            "SourceMode": source,
            "RawPeakMinDistanceSeconds": config.raw_peak_min_distance_s,
            "RawPeakThresholdPercentile": config.raw_peak_threshold_percentile,
            "IBIMinMilliseconds": config.ibi_min_ms,
            "IBIMaxMilliseconds": config.ibi_max_ms,
            "MaxArtifactPercentPerSegment": config.max_edited_percent,
            "SegmentDurationSeconds": config.segment_duration_s,
            "ExpectedSegments": config.expected_segments,
            "LFBandHz": list(config.lf_band_hz),
            "HFRSABandHz": list(config.hf_rsa_band_hz),
            "SpectralWindow": config.spectral_window,
            "SpectralDetrend": config.spectral_detrend,
            "SpectralInterpolateBandEdges": config.spectral_interpolate_band_edges,
            "SpectralTimeMode": config.spectral_time_mode,
            "SpectralOneSidedDensity": config.spectral_one_sided_density,
            "SpectralPowerScale": config.spectral_power_scale,
        },
        "Columns": columns,
    }
    time_base = (metadata or {}).get("file_information", {}).get("time_base")
    if time_base is not None:
        sidecar["SamplingFrequency"] = time_base
    return sidecar


def _column_description(col: str) -> dict[str, str]:
    units = "ms" if col.endswith("_ms") or col in {"ibi_ms", "raw_ibi_ms"} else "n/a"
    return {"Description": col.replace("_", " "), "Units": units}


def _segment_onsets(frame: pd.DataFrame, config: RSAConfig) -> pd.DataFrame:
    out = frame.copy()
    if "segment" in out.columns and "onset" not in out.columns:
        seg = pd.to_numeric(out["segment"], errors="coerce")
        out.insert(0, "duration", config.segment_duration_s)
        out.insert(0, "onset", (seg - 1) * config.segment_duration_s)
    return out


def _ibi_onsets(ibi: pd.DataFrame, config: RSAConfig) -> pd.Series:
    segment = pd.to_numeric(ibi["segment"], errors="coerce")
    values = pd.to_numeric(ibi["ibi_ms"], errors="coerce").fillna(0.0)
    onsets = []
    for _, seg in ibi.assign(_duration=values / 1000.0).groupby(segment, sort=False):
        start = (float(seg["segment"].iloc[0]) - 1.0) * config.segment_duration_s
        cumulative = seg["_duration"].cumsum().shift(fill_value=0.0)
        onsets.extend((start + cumulative).tolist())
    return pd.Series(onsets, index=ibi.index)


def _entities_from_recording(recording_id: str, task_label: str) -> dict[str, str]:
    subject = recording_id
    session = "01"
    run = "01"
    match = re.match(r"(.+?)_(\d+)_SE(\d+)_RSA$", recording_id)
    if match:
        subject, run, session_num = match.groups()
        session = f"SE{session_num}"
    return {
        "sub": _bids_label(subject),
        "ses": _bids_label(session),
        "task": _bids_label(task_label),
        "run": _bids_label(run),
    }


def _entity_stem(entities: dict[str, str]) -> str:
    return f"sub-{entities['sub']}_ses-{entities['ses']}_task-{entities['task']}_run-{entities['run']}"


def _bids_label(value: object) -> str:
    text = str(value)
    text = re.sub(r"[^A-Za-z0-9]+", "", text)
    return text or "unknown"
